version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.12  # Use Python 3.12
    working_directory: ~/mlops  # Ensure this matches your actual directory

  docker-executor:
    docker:
      - image: docker:20.10.14
    working_directory: ~/mlops

jobs:
  clone_repo:
    executor: python-executor
    steps:
      - checkout

  setup_python_env:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Set Up Python Environment
          command: |
            python3 -m venv venv  # Create venv if it doesn't exist
            ls -la  # Check if venv is created
            echo "Python version:"
            python --version
            echo "Activating venv..."
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install pytest pytest-cov
      - persist_to_workspace:
          root: .
          paths:
            - venv  # Save venv for later steps

  run_unit_tests:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/mlops
      - run:
          name: Run Unit Tests
          command: |
            . venv/bin/activate
            pytest tests/ --junitxml=test-results.xml --cov=. --cov-report=xml
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: test-results.xml

  train_model:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/mlops
      - run:
          name: Train Model
          command: |
            . venv/bin/activate
            python train.py
            pytest tests/test_train.py --junitxml=test-results.xml --cov=. --cov-report=xml

  run_integration_tests:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/mlops
      - run:
          name: Run Integration Tests
          command: |
            . venv/bin/activate
            pytest tests/integration --junitxml=test-results.xml --cov=. --cov-report=xml
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: test-results.xml

  build_docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            echo "${DOCKER_PASS}" | docker login ghcr.io -u ${DOCKER_USER} --password-stdin
            docker build -t ghcr.io/onyesi-john/mlops:latest .

  push_docker:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push Docker Image to GitHub Container Registry
          command: |
            echo "${DOCKER_PASS}" | docker login ghcr.io -u ${DOCKER_USER} --password-stdin
            docker push ghcr.io/onyesi-john/mlops:latest

  monitor_model:
    executor: python-executor
    steps:
      - run:
          name: Monitor Model Performance
          command: |
            curl http://localhost:9090/api/v1/query?query=loss

  trigger_retrain:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/mlops
      - run:
          name: Check Model Performance & Retrain
          command: |
            . venv/bin/activate
            loss=$(python check_loss.py)
            if (( $(echo "$loss > 0.5" | bc -l) )); then
              python retrain.py
            fi

workflows:
  version: 2
  pipeline:
    jobs:
      - clone_repo
      - setup_python_env:
          requires:
            - clone_repo
      - run_unit_tests:
          requires:
            - setup_python_env
      - train_model:
          requires:
            - run_unit_tests
      - run_integration_tests:
          requires:
            - train_model
      - build_docker:
          requires:
            - run_integration_tests
      - push_docker:
          requires:
            - build_docker
      - monitor_model:
          requires:
            - push_docker
      - trigger_retrain:
          requires:
            - monitor_model
